name: saas-web-app

volumes:
  # region Cloud services
  pgdata:
  # endregion

networks:
  saas-web-app-network:
    driver: bridge
    attachable: true

  shared-network:
    external: true
    name: shared-network

services:
  st-web-app:
    container_name: st-web-app
    restart: unless-stopped
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ../:/app
    networks:
      - saas-web-app-network
      - shared-network

  # region Cloud services
  st-postgres:
    container_name: st-postgres
    image: postgres:17
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - saas-web-app-network
  
  st-ngrok:
    container_name: st-ngrok
    image: ngrok/ngrok:alpine
    restart: unless-stopped
    env_file:
      - ./.env
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040
    networks:
      - saas-web-app-network
  
  # st-permitio:
  #   container_name: st-permitio
  #   image: permitio/pdp-v2:latest
  #   # restart: always
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 7766:7000
  #   networks:
  #     - saas-web-app-network
  
  # endregion

